//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 07:43:20 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bookong.net/maven/plugin/configreplace/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.bookong.maven.plugin.sdk.xml.cr;
