//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.24 at 10:19:24 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://funshion.com/maven/plugin/configreplace/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.funshion.maven.plugin.sdk.xml.cr;
